// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recipes.Service.Data.Contexts;

namespace Recipes.Service.Migrations
{
    [DbContext(typeof(RecipeContext))]
    partial class RecipeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WhyNotConfirmed")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentText = "Tatlı çok güzel olmuş.",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 126, DateTimeKind.Local).AddTicks(194),
                            EmailAddress = "cnrshn@gmail.com",
                            Fullname = "Caner Sahin",
                            IsConfirmed = true,
                            IsDeleted = false,
                            RecipeId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CommentText = "Güzel bir börek olmuş",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 126, DateTimeKind.Local).AddTicks(3407),
                            EmailAddress = "cnrshn@gmail.com",
                            Fullname = "Caner Sahin",
                            IsConfirmed = true,
                            IsDeleted = false,
                            RecipeId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CommentText = "Tatlıya bayıldım...",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 126, DateTimeKind.Local).AddTicks(3454),
                            EmailAddress = "cnrshn@gmail.com",
                            Fullname = "Caner Sahin",
                            IsConfirmed = true,
                            IsDeleted = false,
                            RecipeId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CommentText = "Tatlıya bayıldım...",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 126, DateTimeKind.Local).AddTicks(3458),
                            EmailAddress = "cnrshn@gmail.com",
                            Fullname = "Caner Sahin",
                            IsConfirmed = true,
                            IsDeleted = false,
                            RecipeId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CommentText = "Tatlıya bayıldım...",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 126, DateTimeKind.Local).AddTicks(3462),
                            EmailAddress = "cnrshn@gmail.com",
                            Fullname = "Caner Sahin",
                            IsConfirmed = true,
                            IsDeleted = false,
                            RecipeId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CommentText = "Tatlıya bayıldım...",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 126, DateTimeKind.Local).AddTicks(3467),
                            EmailAddress = "cnrshn@gmail.com",
                            Fullname = "Caner Sahin",
                            IsConfirmed = true,
                            IsDeleted = false,
                            RecipeId = 6,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CommentText = "Tatlıya bayıldım...",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 126, DateTimeKind.Local).AddTicks(3472),
                            EmailAddress = "cnrshn@gmail.com",
                            Fullname = "Caner Sahin",
                            IsConfirmed = true,
                            IsDeleted = false,
                            RecipeId = 7,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CommentText = "Tatlıya bayıldım...",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 126, DateTimeKind.Local).AddTicks(3476),
                            EmailAddress = "cnrshn@gmail.com",
                            Fullname = "Caner Sahin",
                            IsConfirmed = true,
                            IsDeleted = false,
                            RecipeId = 8,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.FoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CategoryPicture")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WhyNotConfirmed")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FoodCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryDescription = "Tatlı Kategorisi",
                            CategoryName = "Tatlılar",
                            CategoryPicture = "default.jpg",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 106, DateTimeKind.Local).AddTicks(7722),
                            IsConfirmed = true,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryDescription = "Börek Kategorisi",
                            CategoryName = "Börekler",
                            CategoryPicture = "default.jpg",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 107, DateTimeKind.Local).AddTicks(1004),
                            IsConfirmed = true,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryDescription = "Çorba Kategorisi",
                            CategoryName = "Çorbalar",
                            CategoryPicture = "default.jpg",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 107, DateTimeKind.Local).AddTicks(1062),
                            IsConfirmed = true,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryDescription = "Kek Kategorisi",
                            CategoryName = "Kekler",
                            CategoryPicture = "default.jpg",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 107, DateTimeKind.Local).AddTicks(1068),
                            IsConfirmed = true,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryDescription = "Makarna Kategorisi",
                            CategoryName = "Makarnalar",
                            CategoryPicture = "default.jpg",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 107, DateTimeKind.Local).AddTicks(1075),
                            IsConfirmed = true,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryDescription = "Pasta Kategorisi",
                            CategoryName = "Pastalar",
                            CategoryPicture = "default.jpg",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 107, DateTimeKind.Local).AddTicks(1081),
                            IsConfirmed = true,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CategoryDescription = "Kahvaltı Kategorisi",
                            CategoryName = "Kahvaltılıklar",
                            CategoryPicture = "default.jpg",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 107, DateTimeKind.Local).AddTicks(1086),
                            IsConfirmed = true,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CategoryDescription = "Kurabiye Kategorisi",
                            CategoryName = "Kurabiyeler",
                            CategoryPicture = "default.jpg",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 107, DateTimeKind.Local).AddTicks(1091),
                            IsConfirmed = true,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CategoryDescription = "Salata Kategorisi",
                            CategoryName = "Salatalar",
                            CategoryPicture = "default.jpg",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 107, DateTimeKind.Local).AddTicks(1096),
                            IsConfirmed = true,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CategoryDescription = "Sulu Yemek Kategorisi",
                            CategoryName = "Sulu Yemekler",
                            CategoryPicture = "default.jpg",
                            CreateDate = new DateTime(2021, 2, 7, 22, 19, 6, 107, DateTimeKind.Local).AddTicks(1101),
                            IsConfirmed = true,
                            IsDeleted = false,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("CookingTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FoodPicture")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FoodTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PersonSize")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("PreparationTime")
                        .HasColumnType("time");

                    b.Property<string>("RecipeDetail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SeoAuthor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("SeoTags")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<string>("WhyNotConfirmed")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("FoodCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentCount = 0,
                            CookingTime = new TimeSpan(0, 0, 15, 0, 0),
                            CreateTime = new DateTime(2021, 2, 7, 22, 19, 6, 119, DateTimeKind.Local).AddTicks(6111),
                            FoodCategoryId = 1,
                            FoodName = "Kadayif Tatlısı",
                            FoodPicture = "default.jpg",
                            FoodTitle = "guzel tatli",
                            IsConfirmed = true,
                            IsDeleted = false,
                            Material = "kadayıf tarifi malzemeler listesi, html text editor ile yazılacak.",
                            PersonSize = 4,
                            PreparationTime = new TimeSpan(0, 0, 25, 0, 0),
                            RecipeDetail = "15 dk pişir, soğut, servis et vs.",
                            SeoAuthor = "Caner Sahin",
                            SeoDescription = "Kadayif tatlisi tarifi.",
                            SeoTags = "birinci, yemek, tarifi",
                            UserId = 1,
                            ViewCount = 400
                        },
                        new
                        {
                            Id = 2,
                            CommentCount = 0,
                            CookingTime = new TimeSpan(0, 0, 15, 0, 0),
                            CreateTime = new DateTime(2021, 2, 7, 22, 19, 6, 120, DateTimeKind.Local).AddTicks(3707),
                            FoodCategoryId = 2,
                            FoodName = "Avcı Böreği",
                            FoodPicture = "default.jpg",
                            FoodTitle = "Tatlı tarifinin kısa bir başlığı.",
                            IsConfirmed = true,
                            IsDeleted = false,
                            Material = "avcı böreği tarifi malzemeler listesi, html text editor ile yazılacak.",
                            PersonSize = 4,
                            PreparationTime = new TimeSpan(0, 0, 25, 0, 0),
                            RecipeDetail = "15 dk pişir, soğut, servis et vs.",
                            SeoAuthor = "Caner Sahin",
                            SeoDescription = "Avcı böreği tarifi.",
                            SeoTags = "börek, avcı, tarif",
                            UserId = 1,
                            ViewCount = 299
                        },
                        new
                        {
                            Id = 3,
                            CommentCount = 0,
                            CookingTime = new TimeSpan(0, 0, 15, 0, 0),
                            CreateTime = new DateTime(2021, 2, 7, 22, 19, 6, 120, DateTimeKind.Local).AddTicks(3810),
                            FoodCategoryId = 3,
                            FoodName = "Ispanak Yemeği",
                            FoodPicture = "default.jpg",
                            FoodTitle = "Tatlı tarifinin kısa bir başlığı.",
                            IsConfirmed = true,
                            IsDeleted = false,
                            Material = "avcı böreği tarifi malzemeler listesi, html text editor ile yazılacak.",
                            PersonSize = 4,
                            PreparationTime = new TimeSpan(0, 0, 25, 0, 0),
                            RecipeDetail = "15 dk pişir, soğut, servis et vs.",
                            SeoAuthor = "Caner Sahin",
                            SeoDescription = "Avcı böreği tarifi.",
                            SeoTags = "börek, avcı, tarif",
                            UserId = 2,
                            ViewCount = 299
                        },
                        new
                        {
                            Id = 4,
                            CommentCount = 0,
                            CookingTime = new TimeSpan(0, 0, 15, 0, 0),
                            CreateTime = new DateTime(2021, 2, 7, 22, 19, 6, 120, DateTimeKind.Local).AddTicks(3819),
                            FoodCategoryId = 4,
                            FoodName = "Domates Yemeği",
                            FoodPicture = "default.jpg",
                            FoodTitle = "Tatlı tarifinin kısa bir başlığı.",
                            IsConfirmed = true,
                            IsDeleted = false,
                            Material = "avcı böreği tarifi malzemeler listesi, html text editor ile yazılacak.",
                            PersonSize = 4,
                            PreparationTime = new TimeSpan(0, 0, 25, 0, 0),
                            RecipeDetail = "15 dk pişir, soğut, servis et vs.",
                            SeoAuthor = "Caner Sahin",
                            SeoDescription = "Avcı böreği tarifi.",
                            SeoTags = "börek, avcı, tarif",
                            UserId = 2,
                            ViewCount = 299
                        },
                        new
                        {
                            Id = 5,
                            CommentCount = 0,
                            CookingTime = new TimeSpan(0, 0, 15, 0, 0),
                            CreateTime = new DateTime(2021, 2, 7, 22, 19, 6, 120, DateTimeKind.Local).AddTicks(3827),
                            FoodCategoryId = 5,
                            FoodName = "Patates Yemeği",
                            FoodPicture = "default.jpg",
                            FoodTitle = "Tatlı tarifinin kısa bir başlığı.",
                            IsConfirmed = true,
                            IsDeleted = false,
                            Material = "avcı böreği tarifi malzemeler listesi, html text editor ile yazılacak.",
                            PersonSize = 4,
                            PreparationTime = new TimeSpan(0, 0, 25, 0, 0),
                            RecipeDetail = "15 dk pişir, soğut, servis et vs.",
                            SeoAuthor = "Caner Sahin",
                            SeoDescription = "Avcı böreği tarifi.",
                            SeoTags = "börek, avcı, tarif",
                            UserId = 1,
                            ViewCount = 299
                        },
                        new
                        {
                            Id = 6,
                            CommentCount = 0,
                            CookingTime = new TimeSpan(0, 0, 15, 0, 0),
                            CreateTime = new DateTime(2021, 2, 7, 22, 19, 6, 120, DateTimeKind.Local).AddTicks(3834),
                            FoodCategoryId = 6,
                            FoodName = "Soğan Yemeği",
                            FoodPicture = "default.jpg",
                            FoodTitle = "Tatlı tarifinin kısa bir başlığı.",
                            IsConfirmed = true,
                            IsDeleted = false,
                            Material = "avcı böreği tarifi malzemeler listesi, html text editor ile yazılacak.",
                            PersonSize = 4,
                            PreparationTime = new TimeSpan(0, 0, 25, 0, 0),
                            RecipeDetail = "15 dk pişir, soğut, servis et vs.",
                            SeoAuthor = "Caner Sahin",
                            SeoDescription = "Avcı böreği tarifi.",
                            SeoTags = "börek, avcı, tarif",
                            UserId = 1,
                            ViewCount = 299
                        },
                        new
                        {
                            Id = 7,
                            CommentCount = 0,
                            CookingTime = new TimeSpan(0, 0, 15, 0, 0),
                            CreateTime = new DateTime(2021, 2, 7, 22, 19, 6, 120, DateTimeKind.Local).AddTicks(3906),
                            FoodCategoryId = 7,
                            FoodName = "Böğürtlen Yemeği",
                            FoodPicture = "default.jpg",
                            FoodTitle = "Tatlı tarifinin kısa bir başlığı.",
                            IsConfirmed = true,
                            IsDeleted = false,
                            Material = "avcı böreği tarifi malzemeler listesi, html text editor ile yazılacak.",
                            PersonSize = 4,
                            PreparationTime = new TimeSpan(0, 0, 25, 0, 0),
                            RecipeDetail = "15 dk pişir, soğut, servis et vs.",
                            SeoAuthor = "Caner Sahin",
                            SeoDescription = "Avcı böreği tarifi.",
                            SeoTags = "börek, avcı, tarif",
                            UserId = 2,
                            ViewCount = 299
                        },
                        new
                        {
                            Id = 8,
                            CommentCount = 0,
                            CookingTime = new TimeSpan(0, 0, 15, 0, 0),
                            CreateTime = new DateTime(2021, 2, 7, 22, 19, 6, 120, DateTimeKind.Local).AddTicks(3914),
                            FoodCategoryId = 8,
                            FoodName = "Peynir Yemeği",
                            FoodPicture = "default.jpg",
                            FoodTitle = "Tatlı tarifinin kısa bir başlığı.",
                            IsConfirmed = true,
                            IsDeleted = false,
                            Material = "avcı böreği tarifi malzemeler listesi, html text editor ile yazılacak.",
                            PersonSize = 4,
                            PreparationTime = new TimeSpan(0, 0, 25, 0, 0),
                            RecipeDetail = "15 dk pişir, soğut, servis et vs.",
                            SeoAuthor = "Caner Sahin",
                            SeoDescription = "Avcı böreği tarifi.",
                            SeoTags = "börek, avcı, tarif",
                            UserId = 1,
                            ViewCount = 299
                        });
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "75f625e0-b3a9-44cb-9fcb-75c643378f15",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            RoleDescription = "Tüm yetkilere sahip kullanıcıdır."
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "d4bb8776-a3bc-4061-8028-f8a2680a9028",
                            Name = "Editor",
                            NormalizedName = "EDITOR",
                            RoleDescription = "Tarif ve kategori ekleyebilir fakat silemez, Kullanıcılar ve roller sayfalarını görüntüleyemez."
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "fd739c08-7b01-49af-9130-f0d57dadb43c",
                            Name = "Member",
                            NormalizedName = "MEMBER",
                            RoleDescription = "Üye olan herkese atanır, tarif yazabilirler ve yorum bırakabilirler, admin veya editor tarafından onaylanması gerekir. Kullanıcılar, roller ve çöp kutusu sayfalarını görüntüleyemez."
                        });
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("About")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Fullname")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "1 id'li kullanıcı",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4e41fe13-aa0b-433d-a2fd-1d19b26aa4d1",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            Fullname = "Caner Sahin",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEPIcxm4TUjnYEZxOguG4YxNFNTsdcbuPA0ztxAc0bej9izCpBXHBbbRGDVUXpPmaYQ==",
                            PhoneNumber = "00905425612223",
                            PhoneNumberConfirmed = true,
                            Picture = "default.jpg",
                            SecurityStamp = "4347190f-058e-4a9e-8ea9-79eb794fb294",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            About = "2 id'li kullanıcı",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5894cb61-e054-404c-ae81-b642c332d169",
                            Email = "editor@gmail.com",
                            EmailConfirmed = true,
                            Fullname = "Caner Sahin",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EDITOR@GMAIL.COM",
                            NormalizedUserName = "EDITOR",
                            PasswordHash = "AQAAAAEAACcQAAAAEHrzAyyg0KALy5QGbcsQZTOIzj/ged0r7qnUkyzeOrgRgnsRWwGF0xK8wctDoLf9IA==",
                            PhoneNumber = "00905425612223",
                            PhoneNumberConfirmed = true,
                            Picture = "default.jpg",
                            SecurityStamp = "be6af09d-e703-4634-b53d-bbdd65563183",
                            TwoFactorEnabled = false,
                            UserName = "Editor"
                        });
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.UserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.Comment", b =>
                {
                    b.HasOne("Recipes.Service.Core.Concrete.Entities.Recipe", "Recipe")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Recipes.Service.Core.Concrete.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.FoodCategory", b =>
                {
                    b.HasOne("Recipes.Service.Core.Concrete.Entities.User", "User")
                        .WithMany("FoodCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.Recipe", b =>
                {
                    b.HasOne("Recipes.Service.Core.Concrete.Entities.FoodCategory", "FoodCategory")
                        .WithMany("Recipes")
                        .HasForeignKey("FoodCategoryId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Recipes.Service.Core.Concrete.Entities.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("FoodCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.RoleClaim", b =>
                {
                    b.HasOne("Recipes.Service.Core.Concrete.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.UserClaim", b =>
                {
                    b.HasOne("Recipes.Service.Core.Concrete.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.UserLogin", b =>
                {
                    b.HasOne("Recipes.Service.Core.Concrete.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.UserRole", b =>
                {
                    b.HasOne("Recipes.Service.Core.Concrete.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recipes.Service.Core.Concrete.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.UserToken", b =>
                {
                    b.HasOne("Recipes.Service.Core.Concrete.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.FoodCategory", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.Recipe", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Recipes.Service.Core.Concrete.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FoodCategories");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
